### ISSUE TITLE
Plugins appear multiple times

### ISSUE THREAD

**Issue by frankier** [divad12/vim-awesome#72] opened 2015-09-20 10:35 UTC
Eg look at: http://vimawesome.com/?q=vimtex links to http://vimawesome.com/plugin/vimtex-forever-and-always ; http://vimawesome.com/plugin/vimtex-shouldve-said-no and http://vimawesome.com/plugin/vimtex-long-live and more.

Is someone spamming the plugin submissions? Can we make it so a given github url is only allowed one vimawesome entry?

**Comment by superscript18** [comment] 2015-09-21 19:09
+1

**Comment by captbaritone** [comment] 2015-09-21 21:16
Duplicate of https://github.com/divad12/vim-awesome/issues/68, https://github.com/divad12/vim-awesome/issues/64

**Comment by captbaritone** [comment] 2016-02-29 18:16
Closing as a duplicate of #64.

**Closed by captbaritone** 2016-02-29 18:16 UTC
