### ISSUE TITLE
page 5 is full of powerline

### ISSUE THREAD

**Issue by oinirio** [divad12/vim-awesome#68] opened 2015-06-22 19:53 UTC
Title explains it good

**Comment by captbaritone** [comment] 2015-06-22 20:12
URLS are interesting:

* http://vimawesome.com/plugin/powerline-safe-and-sound
* http://vimawesome.com/plugin/powerline-the-story-of-us
* http://vimawesome.com/plugin/powerline-ours
* http://vimawesome.com/plugin/powerline-enchanted
* http://vimawesome.com/plugin/powerline-everything-has-changed
* http://vimawesome.com/plugin/powerline-treacherous
* http://vimawesome.com/plugin/powerline-mine
* http://vimawesome.com/plugin/powerline-forever-and-always

**Comment by dkns** [comment] 2015-06-27 20:52
Also reported here: #64

**Comment by captbaritone** [comment] 2016-02-29 18:16
Closing as a duplicate of #64.

**Closed by captbaritone** 2016-02-29 18:16 UTC
