### ISSUE TITLE
Vundle appearing multiple times

### ISSUE THREAD

**Issue by jkup** [divad12/vim-awesome#74] opened 2015-12-06 03:19 UTC
I'm seeing vundle showing up a lot on the home page currently.
![screen shot 2015-12-04 at 11 49 24 pm](https://cloud.githubusercontent.com/assets/490294/11611478/1add41f0-9b85-11e5-9737-285a9918466b.png)

**Comment by Delapouite** [comment] 2015-12-08 21:41
Yes, long time bug mentioned a few times already but with unfortunately no adequate measure to fix it : 

the project is currently dead.

**Comment by divad12** [comment] 2015-12-09 02:28
We're looking for a maintainer. Please email `emacs@vimawesome.com` if you're interested.

**Comment by divad12** [comment] 2015-12-14 23:00
If anyone wants to look into this, I wrote a report for a school project on this a year+ ago:

https://www.dropbox.com/s/24owxihtek7vau9/report.pdf?dl=0

**Comment by Shougo** [comment] 2015-12-14 23:16
@divad12 It is the great article!  I will look into it.

**Comment by divad12** [comment] 2015-12-14 23:19
Thank you @Shougo! :)

**Comment by Shougo** [comment] 2015-12-14 23:31
This project is important for Vim/neovim.
I want to support it.
Unfotunately, I have not much experience/time for it.

**Comment by Shougo** [comment] 2015-12-14 23:32
I think the best is to create the organization for VimAwesome.
And look for the new maintainers from Vim/neovim users.

**Comment by Shougo** [comment] 2015-12-14 23:41
@divad12 Could you announce it in neovim/vim_dev MLs or Vim reddit page?

**Comment by Delapouite** [comment] 2015-12-15 07:24
Absolutely, a GitHub organization is the way to go.

**Comment by divad12** [comment] 2015-12-16 05:35
Happy to migrate to an org once we find a new maintainer.

**Comment by aerohit** [comment] 2015-12-16 21:51
Hi @divad12 I am trying to run the site locally, but I fail at step 6 and 7

```
(vim-awesome)vagrant@vagrant-box:~/vim-awesome$ make init_db
PYTHONPATH=. python db/init_db.py
Traceback (most recent call last):
  File "db/init_db.py", line 17, in <module>
    ensure_tables_and_indices()
  File "db/init_db.py", line 10, in ensure_tables_and_indices
    db.github_repos.PluginGithubRepos.ensure_table()
  File "/home/vagrant/vim-awesome/db/github_repos.py", line 68, in ensure_table
    cls.ensure_blacklisted_repos()
  File "/home/vagrant/vim-awesome/db/github_repos.py", line 80, in ensure_blacklisted_repos
    'is_blacklisted': True,
  File "/home/vagrant/vim-awesome/db/github_repos.py", line 105, in upsert_with_owner_repo
    db_repo = cls.get_with_owner_repo(repo['owner'], repo['repo_name'])
  File "/home/vagrant/vim-awesome/db/github_repos.py", line 91, in get_with_owner_repo
    return db.util.get_first(query)
  File "/home/vagrant/vim-awesome/db/util.py", line 13, in get_first
    results = list(query.limit(1).run(r_conn()))
  File "/home/vagrant/vim-awesome/vim-awesome/local/lib/python2.7/site-packages/rethinkdb/ast.py", line 75, in run
    return c._start(self, **global_optargs)
  File "/home/vagrant/vim-awesome/vim-awesome/local/lib/python2.7/site-packages/rethinkdb/net.py", line 212, in _start
    return self._send_query(query, global_optargs)
  File "/home/vagrant/vim-awesome/vim-awesome/local/lib/python2.7/site-packages/rethinkdb/net.py", line 313, in _send_query
    self._check_error_response(response, query.term)
  File "/home/vagrant/vim-awesome/vim-awesome/local/lib/python2.7/site-packages/rethinkdb/net.py", line 286, in _check_error_response
    raise RqlRuntimeError(message, term, frames)
rethinkdb.errors.RqlRuntimeError: Index `owner_repo` was not found on table `vim_awesome.plugin_github_repos`. in:
r.table('plugin_github_repos').get_all(['sstephenson', 'bats'], index='owner_repo').limit(1)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
make: *** [init_db] Error 1
```

```
(vim-awesome)vagrant@vagrant-box:~/vim-awesome$ rethinkdb restore -i vim_awesome rethinkdb_dump_2015-12-15.tar.gz
Unzipping archive file...
  Done (1 seconds)
Importing from directory...
importing with args: ['rethinkdb-import', '--connect', 'localhost:28015', '--directory', '/tmp/tmpnWOvFn', '--auth', '', '--clients', '8', '--import', 'vim_awesome']
Error: The following tables already exist, run with --force to import into the existing tables:
  vim_awesome.plugin_github_repos
  vim_awesome.plugins
  vim_awesome.tags
Error: rethinkdb-import failed
```

```
(vim-awesome)vagrant@vagrant-box:~/vim-awesome$ rethinkdb restore --force -i vim_awesome rethinkdb_dump_2015-12-15.tar.gz
Unzipping archive file...
  Done (1 seconds)
Importing from directory...
importing with args: ['rethinkdb-import', '--connect', 'localhost:28015', '--directory', '/tmp/tmp2BtAyl', '--auth', '', '--clients', '8', '--import', 'vim_awesome', '--force']
[                                        ]   0%
0 rows imported in 7 tables
ReQL error during 'create table': Could not connect to localhost:28015. Error: [Errno 111] Connection refused
In file: /tmp/tmp2BtAyl/vim_awesome/plugin_github_repos.json
ReQL error during 'create table': Could not connect to localhost:28015. Error: [Errno 111] Connection refused
In file: /tmp/tmp2BtAyl/vim_awesome/tags.json
ReQL error during 'create table': Connection is closed.
In file: /tmp/tmp2BtAyl/vim_awesome/github_repos.json
ReQL error during 'create table': Could not connect to localhost:28015. Error: [Errno 111] Connection refused
In file: /tmp/tmp2BtAyl/vim_awesome/dotfiles_github_repos.json
ReQL error during 'create table': Could not connect to localhost:28015. Error: [Errno 111] Connection refused
In file: /tmp/tmp2BtAyl/vim_awesome/plugins.json
ReQL error during 'create table': Could not connect to localhost:28015. Error: [Errno 111] Connection refused
In file: /tmp/tmp2BtAyl/vim_awesome/plugin_repos.json
ReQL error during 'create table': Could not connect to localhost:28015. Error: [Errno 111] Connection refused
In file: /tmp/tmp2BtAyl/vim_awesome/submitted_plugins.json
Errors occurred during import
Error: rethinkdb-import failed
```

I haven't worked with rethinkdb before, so some pointers would be of immense help.

**Comment by aerohit** [comment] 2015-12-16 21:52
And besides that, do you already have any clue about the cause of the bug?

**Comment by spicyj** [comment] 2015-12-16 22:28
The server is currently running rethinkdb 1.16.1 – perhaps you have a newer version where something's changed? We should probably upgrade but I don't know what needs changing.

**Comment by aerohit** [comment] 2015-12-17 09:45
@spicyj ok cool, let me try that in the evening after work.

**Comment by Shougo** [comment] 2015-12-17 11:06
> Happy to migrate to an org once we find a new maintainer.

:+1: 
I will search a new maintainer.

**Comment by delirehberi** [comment] 2016-01-09 17:44
I'm candidate for maintaining.

**Comment by captbaritone** [comment] 2016-02-29 18:16
Closing as duplicate of #64.

**Closed by captbaritone** 2016-02-29 18:16 UTC
